### ISSUE TITLE
Problema nell'esecuzione del comando npm run build

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-pagine-statiche#103]
Buongiono,
eseguendo il comando "npn run build" ottengo il seguente messaggio:

> design-comuni-pagine-statiche@2.2.0 build
> cross-env NODE_ENV=production webpack --config ./config/webpack.config.js

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn webpack',
  path: 'webpack',
  spawnargs: [ '--config', './config/webpack.config.js' ]
}

Di cosa si tratta?

Grazie.

**Comment by marco-nanni** [comment]
Risolto.
Potete chiudere la isse.

Grazie.

**Comment by astagi** [comment]
Ottimo @marco-nanni

**Comment by marco-nanni** [comment]
@astagi Ci tenevo comunque a precisare che oltre ai comandi che avete indicato in descrizione occorre accertarsi della prsenza del modulo cross-env,  webpack-dev-server e webpack-cli.
Nel caso installarli con i seguenti comandi:

```
npm install --global cross-env
npm install -g webpack-dev-server
npm install -D webpack-cli
```

Dopo di ché eseguire `npm run start` e `npm run build`.
