### ISSUE TITLE
Errore padding componente Accordion

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#116]
Ciao,
https://github.com/italia/design-comuni-pagine-statiche/blob/main/src/components/cmp-accordion/_cmp-accordion.scss
Alla riga 101
```
      @include media-breakpoint-up(sm) {
        padding-left: 0.875rem 0 0;
      }
```

**Comment by enrimk** [comment]
Il bug [è ancora lì](https://github.com/italia/design-comuni-pagine-statiche/blob/374ba8d037b1229979fb4afe43ca4277cf5f0fdf/src/components/cmp-accordion/_cmp-accordion.scss#L102).

Per chiarire:
la regola è sintatticamente invalida, _padding-left_ prende un valore solo, non tre come invece può fare _padding_.
Quindi la riga non ha effetto, e se non serve è meglio toglierla.

A cosa serve la regola? Si applica a `.accordion-header .accordion-button`. È un piccolo riallineamento su mobile (tablet) dei titoli [dell'accordion in pagine come questa (tab _Attività_)](https://italia.github.io/design-comuni-pagine-statiche/servizi/servizi-pagamento-area-personale.html), ma l'allineamento non sarebbe comunque preciso, e non si riesce a ricavare dal contesto se si intendeva usare _padding_ o _padding-left_.
