### ISSUE TITLE
Errore apertura filtri pagina di ricerca da mobile

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#118]
Nella pagina https://italia.github.io/design-comuni-pagine-statiche/sito/risultati-ricerca.html il pulsante "filtra" in versione mobile non funziona

![immagine](https://github.com/italia/design-comuni-pagine-statiche/assets/20642463/4f7e6045-51d7-4444-b0fc-0460165371d7)

in console è restituito il seguente errore

```
Uncaught TypeError: this._config is undefined
    _initializeBackDrop https://italia.github.io/design-comuni-pagine-statiche/assets/bootstrap-italia/dist/js/bootstrap-italia.bundle.min.js:397
    Modal$2 https://italia.github.io/design-comuni-pagine-statiche/assets/bootstrap-italia/dist/js/bootstrap-italia.bundle.min.js:397
    getOrCreateInstance https://italia.github.io/design-comuni-pagine-statiche/assets/bootstrap-italia/dist/js/bootstrap-italia.bundle.min.js:50
    <anonymous> https://italia.github.io/design-comuni-pagine-statiche/assets/bootstrap-italia/dist/js/bootstrap-italia.bundle.min.js:397
    r https://italia.github.io/design-comuni-pagine-statiche/assets/bootstrap-italia/dist/js/bootstrap-italia.bundle.min.js:44
bootstrap-italia.bundle.min.js:397:1989
```

**Comment by enrimk** [comment]
@astagi 
Qualcuno dovrebbe spiegare a _Stalebot_ che l'issue non è risolto e completato, c'è ancora.

La causa immagino è che nell'html [manca](https://github.com/italia/design-comuni-pagine-statiche/blob/374ba8d037b1229979fb4afe43ca4277cf5f0fdf/src/pages/sito/risultati-ricerca.hbs#L162) la dialog [#modal-categories con i filtri di ricerca](https://github.com/italia/design-comuni-pagine-statiche/blob/374ba8d037b1229979fb4afe43ca4277cf5f0fdf/src/components/cmp-modal/modal-filter-categories.hbs#L1C95-L1C111), che su mobile dovrebbe aprirsi [cliccando sul pulsante](https://github.com/italia/design-comuni-pagine-statiche/blob/374ba8d037b1229979fb4afe43ca4277cf5f0fdf/src/pages/sito/risultati-ricerca.hbs#L27-L28)?

---

Un errore js analogo compare sul pulsante Cerca, anche in quel caso come risultato di un html incompleto, [con degli attributi abbozzati](https://github.com/italia/design-comuni-pagine-statiche/blob/374ba8d037b1229979fb4afe43ca4277cf5f0fdf/src/components/cmp-input-search-button/cmp-input-search-button.hbs#L14C25-L14C66) (anche [nella lista risultati](https://github.com/italia/design-comuni-pagine-statiche/blob/374ba8d037b1229979fb4afe43ca4277cf5f0fdf/src/components/cmp-card-latest-messages/cmp-card-latest-messages.hbs#L1C63-L1C115)) che farebbero pensare pure lì all'apertura di qualche dialog - dialog di cui però non si trova traccia né qui né altrove: neanche su Figma ci sono indicazioni di dialog aperte o chiuse dal pulsante Cerca o dagli elementi della lista risultati.

Questi attributi (non funzionanti, pare) [sono stati riportati](https://github.com/italia/design-comuni-wordpress-theme/blob/31628b8a3d5806f773e0cb0c6fb7be08d9cd5c76/search.php#L76-L77) anche [nei template cms](https://github.com/italia/design-comuni-wordpress-theme/blob/31628b8a3d5806f773e0cb0c6fb7be08d9cd5c76/template-parts/search/item.php#L7C50-L7C91), e mi chiedo perché.
