### ISSUE TITLE
Problem in understanding the use of static text fields "Details"

### ISSUE THREAD

**Issue by andreaalbe** [italia/design-comuni-pagine-statiche#133]
Hi, following functional tests, we find that a part of the population can not understand in the static page "Appuntamenti", the section field "Details" because the explanation/subtitle is "Add more details": which makes the subtitle useless. 

Since the field is mandatory, this uncertainty generates stress, and consequently leads the user to call the assistance in order to proceed with the booking.

Isn't it better to think a subtitle maybe more complex like "Specifying the topic or documents inherent the appointment" or something like that?

**Comment by enrimk** [comment]
È un caso di _rogue AI_? Stalebot si ribella al creatore e appiccica malignamente un bel _wontfix_ agli issue di UX (umana)? 😁

**Comment by zetareticoli** [comment]
@andreaalbe Sorry for the late reply, yes, your suggested subtitle could work better than a generic one. 

Since it is a template, everyone can customize the content as they see fit. Anyway, we'll consider your suggestion for the next release. 

Thanks
