### ISSUE TITLE
Errore su componente cmp-nav-tab

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#135]
Il componente usato in questo esempio https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-area-personale.html ha una un'inspiegabile proprietà...
```
.cmp-nav-tab .nav-tabs {
    overflow-x: hidden;
}
```
Questo significa che è inibito lo scroll orizzontale delle tab e da mobile comporta il problema che non è possibile raggiungere le tab che sono fuori dalle dal viewport!

**Comment by zetareticoli** [comment]
Rimosso `wontfix`

**Comment by enrimk** [comment]
_Stalebot_ si dà un po' troppo da fare, bisognerebbe davvero limitarne lo zelo.

Qual è il senso di chiudere un issue [dopo due mesi che non riceve ulteriori commenti](https://github.com/italia/design-comuni-pagine-statiche/blob/374ba8d037b1229979fb4afe43ca4277cf5f0fdf/.github/stale.yml#L1-L4)?
L'urgenza o la validità di un difetto segnalato non dipende dalla lunghezza della discussione.
Tanto più, visto il ritmo piuttosto blando di avanzamento di questi progetti, sia nelle correzioni sia nell'interazione col pubblico.

Non vedo l'utilità di "nascondere" i difetti marcandoli come risolti, artificialmente. Anche al team di sviluppo poi mancherà quel po' di aiuto che una beta pubblica e un issue tracker possono dare; alla fine non si sa più cosa è veramente risolto e cosa no.

Non sembra che sussistano le condizioni per una moderazione automatica "di mano pesante": le nuove segnalazioni non sono poi tante.

O forse, solo per alcune categorie di issue. Ad es. su issue molto molto specifici, al limite della richesta individuale di aiuto/assistenza - che è magari anche opinabile che stiano in un issue tracker in primo luogo. Oppure, strani bug rilevati da un solo utente. In quel caso, una scadenza ha senso: se il problema non si manifesta in generale, magari è un'eccezione che non vale la pena risolvere (e _wontfix_ ci sta). O è un errore di chi ha segnalato - che comunque potrebbe avere nel frattempo risolto, ed è giusto che stia a lui aggiornare gli altri sulla situazione.

Ma su bug oggettivi e accertati, e a volte già presi in carico? Segnarli _wontfix_ non è molto utile, e tanto meno chiuderli.
