### ISSUE TITLE
Aggiornare i template al nuovo Bootstrap Italia (2.7.2 in poi)

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#137]
I template https://italia.github.io/design-comuni-pagine-statiche/ sono fermi alla versione 2.3.5 di BI mentre oggi è stata rilasciata la 2.7.2.
In particolare con [la release della v. 2.7.0](https://github.com/italia/bootstrap-italia/commit/84f095561491ddaa1b6d25003b50b03ddc9e0613) sono stati alterati tutti i rapporti di dimensione dei font il che comporta dover rivedere tutto il layout per ripristinare le dimensioni corrette.

**Comment by zetareticoli** [comment]
Ciao @AlessandroVecchi , è il motivo per cui i templates statici non utilizzano ancora l'ultima versione di BS Italia. Ti consiglio di tornare alla versione precedente.

Stiamo preparando un aggiornamento dei templates con l'ultima versione e un ottimizzazione dei CSS.

Ad ogni modo, il mio consiglio è quello di aprire issue facendo appello ad uno spirito collaborativo. Grazie

**Comment by AlessandroVecchi** [comment]
Ciao,
Scusate @zetareticoli ha chiuso la issue ma contemporanemente mi è stato detto che ci state lavorando.
Ho assoluto bisogno di capire se questo progetto è da considerarsi ancora in sviluppo o meno e se sì avere un'idea di massima delle tempistiche.
Mi dispiace non poter collaborare più attivamente ma ho già i miei progetti da portare avanti.
Grazie

**Comment by AlessandroVecchi** [comment]
> Ciao, stiamo concludendo un lavoro di aggiornamento della UI (Figma) utilizzando tutti gli stili provenienti dal Design System del Paese e UI kit Italia. Questa fase si concluderà approssimativamente la prossima settimana. Dopodiché inizieremo ad aggiornare e ripulire i templates statici e gli assets (css) del modello.

ok, grazie, quindi presumo - visto anche le feste di mezzo - che ci vorrà ancora almeno un mese.

**Comment by zetareticoli** [comment]
Risolto in #155
