### ISSUE TITLE
Virgola extra nel JSON-LD

### ISSUE THREAD

**Issue by tensor5** [italia/design-comuni-pagine-statiche#14]
Nel metatag di  https://italia.github.io/design-comuni-pagine-statiche/sito/template-dettaglio-servizio.html c'è una virgola di troppo alla riga `"addressLocality": "Lorem ipsum",` che lo rende un JSON non valido.

**Comment by zetareticoli** [comment]
Ciao @tensor5 , grazie della segnalazione, provvediamo alla correzione
