### ISSUE TITLE
Errore componente cmp-input-search

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#144]
Ciao,
Mi sono accorto che in versione mobile l'icona della ricerca che c'è nella pagina compare nel menu.

![Screenshot 2023-12-13 145217](https://github.com/italia/design-comuni-pagine-statiche/assets/20642463/b1859df3-be24-45b7-9581-2e09a6dadd15)

Io ho risolto abbassando lo z-index su `.autocomplete-icon` da 5 a 4 ma non so come mai fosse stato scelto questo preciso valore.
Apparentemente non ho notato problemi di comportamento.

**Comment by enrimk** [comment]
Più in generale, visto che `<header/>` e `<main/>` sono nello stesso _stacking context_, ogni tanto ci potrebbero essere anche altri elementi della pagina che "bucano" l'overlay del menù, se capita che abbiano uno z-index > 5.
Infatti 5 è [lo z-index di `.it-header-wrapper`](https://github.com/italia/bootstrap-italia/blob/89a4052e652bdc6c7c89eda9418cce36b41ffdec/src/scss/custom/_header.scss#L6) (anche se questo non sembra in accordo con [la politica di BI in merito](https://github.com/italia/bootstrap-italia/blob/89a4052e652bdc6c7c89eda9418cce36b41ffdec/docs/organizzare-gli-spazi/introduzione.md#z-index)).

**Comment by AlessandroVecchi** [comment]
Ho trovato l'inghippo: con z-index a 4 ed il focus sul campo l'icona sparisce.
Quindi la mia soluzione non è valida, converrebbe quindi innalzare il livello di `it-header-wrapper` verificando però tutte le conseguenze.

**Comment by enrimk** [comment]
Come _hotfix_, io ho usato questo:
```css
.cmp-input-search .input-group {
	z-index: 0;
}
``` 
Stabilisce un _context_ distinto per il contenitore del campo e delle sue decorazioni.
Ha il vantaggio di non affidarsi a _numeri magici_, e di essere un fix localizzato e non interferire con altro (...forse. Con css non si sa mai). 
Lo svantaggio, è lo stesso: che è una toppa locale e non risolve altri possibili casi.
