### ISSUE TITLE
Errore contorno card, su mobile (lista risorse)

### ISSUE THREAD

**Issue by enrimk** [italia/design-comuni-pagine-statiche#146]
Nelle viste di tipo _Lista Risorse_  ([Lista Risorse/Categorie](https://italia.github.io/design-comuni-pagine-statiche/sito/lista-risorse-categorie.html), [Lista Categorie](https://italia.github.io/design-comuni-pagine-statiche/sito/lista-categorie.html), [Novità](https://italia.github.io/design-comuni-pagine-statiche/sito/novita.html), [Vivere il Comune](https://italia.github.io/design-comuni-pagine-statiche/sito/eventi.html)), gli elementi "card" della lista hanno il bordo staccato dallo sfondo, sul margine inferiore, nelle viste fino a `(max-width: 991px)`.

![image](https://github.com/italia/design-comuni-pagine-statiche/assets/93265448/d97a722e-3ae2-43f4-96b8-7f71a345618a)

Il difetto è evidente nelle liste su sfondo colorato; su sfondo bianco viene camuffato.

È causato (anche) dal fatto che BS/BI applica lo sfondo su `.card`, ma [il template applica il bordo sul `div.card-wrapper` contenitore](https://github.com/italia/design-comuni-pagine-statiche/blob/374ba8d037b1229979fb4afe43ca4277cf5f0fdf/src/components/cmp-list-card-img/cmp-list-card-img-hr.hbs#L4-L5) (via classi css).
Su [`.card-wrapper` c'è un `padding-bottom`](https://github.com/italia/bootstrap-italia/blob/18e9d711e1cda4b0d34470287aa175b26c089489/src/scss/custom/_card.scss#L4), che "separa" i due elementi (e che non è chiaro a cosa serva). [Su tablet/desktop, viene tolto](https://github.com/italia/bootstrap-italia/blob/18e9d711e1cda4b0d34470287aa175b26c089489/src/scss/custom/_card.scss#L696).

La soluzione più rapida è fare come è stato fatto nella view [Documenti e Dati](https://italia.github.io/design-comuni-pagine-statiche/sito/documenti-dati.html) (che stranamente è diversa dalle altre liste).
Lì, [è stata aggiunta una classe `.pb-0` al `div.card-wrapper`](https://github.com/italia/design-comuni-pagine-statiche/blob/374ba8d037b1229979fb4afe43ca4277cf5f0fdf/src/components/cmp-list-card-img/cmp-list-card-docs.hbs#L4), che neutralizza il padding.

Sarebbe comunque meglio spostare le classi "di presentazione" da `div.card-wrapper` a `div.card`, per "seguire" lo sfondo.
```html
<div class="card-wrapper pb-0">
  <div class="card no-after border border-light rounded shadow-sm">
```
E sarebbe da riconsiderare l'utilità del padding su .card-wrapper, in BI.

**Comment by enrimk** [comment]
...E peraltro, la classe `.card-wrapper` sembra essere stata pensata per il contenitore _di una lista_, non di un singolo elemento.

È un _flexbox_; e c'è la variante `.card-wrapper.card-teaser-wrapper`, che è esplicitamente [`flex-direction: row`](https://github.com/italia/bootstrap-italia/blob/18e9d711e1cda4b0d34470287aa175b26c089489/src/scss/custom/_card.scss#L19), e un'altra che contiene più _.card_ impilate: [`.card-wrapper.card-column .card+.card`](https://github.com/italia/bootstrap-italia/blob/18e9d711e1cda4b0d34470287aa175b26c089489/src/scss/custom/_card.scss#L13).

Quindi, più che il padding, andrebbe riconsiderato il suo uso nei template.
Bisognerebbe spostarla fuori dai loop.

**Comment by AlessandroVecchi** [comment]
Mi sembrava un deja-vu, l'avevo già segnalato tempo fa: https://github.com/italia/design-comuni-pagine-statiche/issues/66

**Comment by enrimk** [comment]
```diff
--- a/.github/stale.yml
+++ b/.github/stale.yml
@@ -7,4 +7,5 @@ exemptLabels:
   - pinned
   - security
+exempt-all-assignees: true
 # Label to use when marking an issue as stale
 staleLabel: wontfix
``` 

[stale.yml](https://github.com/italia/design-comuni-pagine-statiche/blob/main/.github/stale.yml), [`exempt-all-assignees`](https://github.com/actions/stale?tab=readme-ov-file#exempt-all-assignees)
