### ISSUE TITLE
Visualizzazione link (`inline-block`)

### ISSUE THREAD

**Issue by enrimk** [italia/design-comuni-pagine-statiche#168]
#### *Follow-up da italia/design-comuni-wordpress-theme#314*

Su tutti i tag `<a>` viene applicato indiscriminatamente `display: inline-block`.
In molti casi questo impedisce il corretto layout.

Ad esempio, negli elenchi puntati, come rilevato in [#314](https://github.com/italia/design-comuni-wordpress-theme/issues/314).

Un altro caso, altrettanto comune, è quello di normali link in un qualunque testo di pagina, che siano però lunghi più di una riga o che comunque vadano a capo.

In questa condizione tutti i link, in qualunque zona del sito, si comportano come "box" rettangolari: formano un riquadro a parte, circondato dal testo (in modo simile a come il browser tratta le immagini).

Verosimilmente non è questo il comportamento voluto.
[ NB: La regola css in questione è stata aggiunta allo [stylesheet di reset](https://github.com/italia/design-comuni-pagine-statiche/commit/dfd2414769493cd3fe6a2232d14d43c135899dad). ]

![image](https://github.com/user-attachments/assets/af230441-5862-46f9-a563-dc2a9ad384ae)

**Comment by enrimk** [comment]
Lo scopo dell'aggiunta della regola, stando al [messaggio di commit](https://github.com/italia/design-comuni-pagine-statiche/commit/dfd2414769493cd3fe6a2232d14d43c135899dad), è per correggere qualcosa nella linea di contorno degli stati _:focus_ dei link.  
In effetti, togliendola, si vede che i link con _focus_ hanno un contorno irregolare.  
Tuttavia, questo si è reso necessario soprattutto perché in Bootstrap Italia si è scelto di [simulare l'outline con un _box-shadow_](https://github.com/italia/design-comuni-pagine-statiche/blob/2066283c7c55068066463479e28cea3129302a88/src/stylesheets/base/_global.scss#L8-L9).
Alla luce di un supporto dei browser per gli elementi di accessibilità che è sicuramente migliorato nel frattempo, andrebbe forse rivisto e aggiustato il ricorso a questi stratagemmi (compreso il _polyfill_ `:not(.focus--mouse)` per simulare `:focus-visible`).

#### Ora:
![errata-visualizzazione-link-modello-comuni_3](https://github.com/user-attachments/assets/30058061-891d-4191-9419-cacd63726840)
#### `<a>` inline:
![errata-visualizzazione-link-modello-comuni_4](https://github.com/user-attachments/assets/f30fd972-328a-4e33-a23d-3475949e5d7e)
#### Normale outline (`:focus`), senza _shadow_:
![errata-visualizzazione-link-modello-comuni__focus--outline](https://github.com/user-attachments/assets/bd05e046-38b9-4d40-8bed-adab634c7dde)
#### `:focus-visible` in browser moderni (Chrome):
![errata-visualizzazione-link-modello-comuni__focus-visible](https://github.com/user-attachments/assets/821d4617-5488-4a4f-baa8-fb61ddbc41e9)


In ogni caso, forse non è poi appropriato che una regola con uno scopo così specifico, e soprattutto non indipendente ma in dipendenza da scelte fatte in altri stylesheet, stia proprio nello stylesheet di reset, che di solito viene usato per cose fondamentali come costituire una base di partenza e uniformare i browser.

**Comment by enrimk** [comment]
Suggerirei, per arginare _Stalebot_ in una funzione più utile:
```diff
diff --git a/.github/stale.yml b/.github/stale.yml
--- .github/stale.yml
+++ .github/stale.yml
@@ -5,4 +5,6 @@
 # Issues with these labels will never be considered stale
 exemptLabels:
   - pinned
   - security
+exemptProjects: true
+exemptAssignees: true

``` 

([exemptProjects](https://github.com/probot/stale/blob/28b78d1d70fed3d550e1de7fe59b0db0b4bae543/README.md?plain=1#L43-L44), [exemptAssignees](https://github.com/probot/stale/blob/28b78d1d70fed3d550e1de7fe59b0db0b4bae543/README.md?plain=1#L49-L50))

**Comment by zetareticoli** [comment]
@enrimk ho aperto PR di fix in draft per testing
