### ISSUE TITLE
denominazione components

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#33]
Ciao,
Scusate la issue forse sciocca.
Qual è la logica per cui alcuni componenti hanno una cartella con prefisso cmp- e altri no?
Quale è la discriminante per cui c'è "cmp-footer" mentre non c'è "cmp-header" e la cartella si chiama invece "header"?
Grazie

**Comment by zetareticoli** [comment]
Ciao @AlessandroVecchi , per questo tipo di domande puoi usare il [canale slack dedicato ](https://developersitalia.slack.com/archives/CME9AD8NN).

Qui su GitHub solo issues tecniche, grazie ;)
