### ISSUE TITLE
Sezione menu scompare se il sito viene visualizzato da un dispositivo mobile.

### ISSUE THREAD

**Issue by IsTk0** [italia/design-comuni-pagine-statiche#4]
**Buongiorno developer**. Oggi ho scaricato il vostro preset, e fin da subito mi sono accorto che simulandolo su un dispositivo mobile (testato su: iPhone 12 pro, iPhone SE 2°Gen, Samsung Galaxy S20 Ultra etc...) la sezione in alto dove spunta Amministrazione Novità etc... **scompare nel nulla**. Non so se è voluto o meno ma non ho trovato nessun corrispettivo ad un altra funzione/funzione analoga nel resto del sito. Dovrebbe esser dovuto alla grandezza dello schermo, ma è tutto risolvibile con un semplice menu a tendina. 

Spero di esservi stato utile dev, fatemi sapere, saluti 👋🏻

**Comment by astagi** [comment]
Ciao @IsTk0 e grazie del report! Potresti allegare qualche screenshot?

**Comment by DeltaFoxtMike** [comment]
Salve, sono un collaboratore di @IsTk0, a breve manderò qui il tutto

**Comment by DeltaFoxtMike** [comment]
https://user-images.githubusercontent.com/85831311/189472915-3deb42bc-2200-48dc-92b4-4d7471be1bf6.mp4

**Comment by DeltaFoxtMike** [comment]
Non so se è un comportamento aspettato, tuttavia sul sito versione mobile sembra non esserci altro modo per accedere a quelle pagine, sennon alla fine della pagina con alcuni dei link presenti lì, buona giornata :)

**Comment by astagi** [comment]
Grazie mille! Sembra che le icone non vengono caricate correttamente e per questo non vedete l'hamburger icon accanto alla label Nome Comune che apre il menu! Avete provato a visualizzare l'anteprima ufficiale? 
https://italia.github.io/design-comuni-pagine-statiche/sito/template-homepage.html

Se visualizzate dalla build vi consiglio di lanciare il tutto con un server di sviluppo locale come 
https://www.npmjs.com/package/http-serve

**Comment by DeltaFoxtMike** [comment]
Ok, ti confermo che nel server di sviluppo in locale funziona perfettamente, per cui è un semplice problema di caricamento di icone come dici tu, meglio, significa che avete fatto un sito impeccabile, bravi! Se possiamo aiutare in altro facci sapere ;)

**Comment by astagi** [comment]
Grazie @DeltaFoxtMike @IsTk0 ! Ogni contributo è sempre ben accetto! Per ogni eventuale discussione rimando anche allo [Slack di Developers Italia](https://slack.developers.italia.it/). A presto! ☺️
