### ISSUE TITLE
Notizia ed Evento: tag sezioni, e titoli

### ISSUE THREAD

**Issue by enrimk** [italia/design-comuni-pagine-statiche#44]
\[question\]
Qual è la ragione dell'uso di `<article />` per suddividere in sezioni i template di [Notizia](https://italia.github.io/design-comuni-pagine-statiche/sito/template-novita-notizia.html) ed [Evento](https://italia.github.io/design-comuni-pagine-statiche/sito/template-novita-evento.html)?  
Nel template [Servizio](https://italia.github.io/design-comuni-pagine-statiche/sito/template-dettaglio-servizio.html) una situazione analoga è stata risolta, credo più appropriatamente, usando `<section />`. C'è un motivo di trattarli diversamente?

Le [specifiche html](https://html.spec.whatwg.org/multipage/sections.html#the-article-element) raccomandano `<article>` per contenuti _"in principle, independently distributable or reusable"_, che non credo sia il caso di queste sezioni.

Inoltre, i titoli delle sezioni sono `<h4>` e saltano dei livelli di gerarchia, potrebbero esserci problemi di accessibilità.

**Comment by AlessandroVecchi** [comment]
Ciao @enrimk 
Perché dici che non sono contenuti riusabili? pensa solo alla condivisione di notizie ed eventi sui social

**Comment by enrimk** [comment]
È riutilizzabile e distribuibile la notizia o l'evento nel suo insieme, non le sue sezioni singolarmente prese.   
Le date un evento, o la lista di documenti allegati a una notizia non hanno un'esistenza indipendente, sono parti correlate strettamente al tutto e non possono essere estratte e pubblicate altrove.

**Comment by AlessandroVecchi** [comment]
> È riutilizzabile e distribuibile la notizia o l'evento nel suo insieme, non le sue sezioni singolarmente prese. Le date un evento, o la lista di documenti allegati a una notizia non hanno un'esistenza indipendente, sono parti correlate strettamente al tutto e non possono essere estratte e pubblicate altrove.

Scusami non avevo guardato bene. In effetti mi sembra strano, io avrei fatto il contrario
```
<article>
  <section></section>
  <section></section>
</article>
```

**Comment by astagi** [comment]
@enrimk il fix dell'h4 è in progress #43 . Formuliamo la risposta alle altre domande asap.
