### ISSUE TITLE
Template argomento

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#54]
Ciao,
La pagina "Argomenti" https://italia.github.io/design-comuni-pagine-statiche/sito/template-argomenti-argomento.html ha un layout diverso dalle altre pagine del modello.
Segnali alcuni errori/incongruenze

1. Il titolo H1 è definito con `<h1 class="mb-3 mb-lg-4 title-xxlarge">Sport</h1>` a differenze della altre pagine dove è `<h1 class="text-black hero-title" data-element="page-name">Amministrazione</h1>`
Quindi oltre al diverso stile (il font risulta più piccolo, non ho capito se è voluto) manca anche il data-element

2. Analogamente il testo sotto al titolo è definito con `<p class="u-main-black text-paragraph-regular-medium mb-60">` al posto di `<div class="hero-text">`

3. è presente un `<h2 class="visually-hidden" id="news-details">Dettagli della notizia</h2>` che mi sembra fuori contesto e non ho capito a cosa serva.

4. il primo h3 "Novità" a risoluzione SM (da 576 a 767px) viene nascosto. Questo perché il suo container ha classe `<div class="bg-grey-card pt-40 pt-md-100 pb-50">` dovrebbe invece avere una classe "pt-sm-100" ma questa non è stata definita nel framework.

5. Segnalo infine che gli eventi sono stati messi insieme alle novità sebbene nella coreografia di navigazione la sezione "eventi" sia stata posizionata sotto "vivere il comune" e non sotto "novità". Per logica dovrebbero avere una riga a se stante oppure, volendo tenerli insieme, rinominare la riga in "novità ed eventi" o qualcosa di simile.

Se trovo altro lo aggiungo ;)

**Comment by zetareticoli** [comment]
Ciao @AlessandroVecchi,

grazie per le tue segnalazioni, sempre molto dettagliate.

Verifichiamo quanto elencato e ti facciamo sapere. Sicuramente i bug saranno presi in carico con urgenza.

**Comment by AlessandroVecchi** [comment]
> Ciao @AlessandroVecchi,
> 
> grazie per le tue segnalazioni, sempre molto dettagliate.
> 
> Verifichiamo quanto elencato e ti facciamo sapere. Sicuramente i bug saranno presi in carico con urgenza. Quali pagine hai usato per il confronto da te elencato?

Ciao,
Le pagine di primo livello (amministrazione, servizi, ecc.)

Guardando adesso velocemente il codice della pagine di dettaglio (notizia, evento) ho visto che il codice dell'h1 è ancora diverso e nella pagina https://italia.github.io/design-comuni-pagine-statiche/sito/template-novita-notizia.html c'è proprio quel h2 che probabilmente è stato riportato per errore nella pagina di argomento.

**Comment by AlessandroVecchi** [comment]
Sempre sulla pagina argomenti, le sezioni relative ad Amministrazione, Servizi e Documenti sono un po' limitate.
Sono presenti solo 3 elementi per riga con un pulsante "vedi tutti" che non si capisce se deve puntare alla pagina generale o all'elenco di tutti gli elementi associati all'argomento.

Sarebbe più funzionale la soluzione già adottata col precedente modello sul comune di Cagliari
https://www.comune.cagliari.it/portale/page/it/arte_e_cultura?contentId=ARG10910
Dove è presente una paginazione degli elementi, quindi senza uscire dal contesto, ed un filtro sui risultati (quest'ultimo sicuramente migliorabile).

Una nota sulla sezione "documenti" che era presente come a se stante nell'architettura del modello 1.0 ma che nel 2.0 è stata spostata sotto "amministrazione".
In teoria, se la pagina argomento deve elencare le sezioni di primo livello, queste dovrebbero essere: Amministrazione, Novità, Servizi e Vivere il comune. 
Per ogni sezione di primo livello potrebbe  esserci un filtro per quelle di secondo livello. Es. per vivere il comune: "eventi" e "luoghi".

Insomma, direi che un po' tutto questo template andrebbe rivisto....

**Comment by AlessandroVecchi** [comment]
Altra segnalazione.
Le righe delle sezioni amministrazione, servizi e documenti sono costruite con le classi flex invece che sulla griglia di boostrap.
Nel caso in cui ci sono 2 elementi anziché 3 essi appaiono disallineati
es.
![immagine](https://user-images.githubusercontent.com/20642463/198241605-b7f2f6c3-3618-4d7c-b639-d80fda78c8e0.png)

Segnalo inoltre che per card-teaser-wrapper non c'è un componente come per altri elementi del modello ma è statico e scritto per esteso ogni volta che viene usato.

**Comment by zetareticoli** [comment]
Chiudo perché risolta in #56
