### ISSUE TITLE
Template Albo Pretorio e Amministrazione Trasparente

### ISSUE THREAD

**Issue by wmasi78** [italia/design-comuni-pagine-statiche#58]
Salve
Non riesco a trovare i template HTML del modello per le pagine "Albo Pretorio" e "Amministrazione Trasparente".
Come riferimento sto usando i siti dei Comuni di Cagliari, Buggerru e Ala ma trovo delle incongruenze rispetto alle linee guida. 
Se consideriamo "Documenti albo pretorio" sono raggiungibili nella sezione "Documenti e dati" presente tra le voci di menu di primo livello.
Qui nasce il mio primo dubbio...se viene indicato questo sito come riferimento mi aspetto come voci di menu di primo livello solo:
- Amministrazione;
- Novità;
- Servizi;
- Vivere il Comune;
- Argomenti.

"Documenti e dati" dovrebbe essere di 2° livello e dovrebbe obbligatoriamente la struttura di una Pagina Lista. 
Solo il Comune di Cagliari, una volta filtrato per tipologia di documento, mi presenta una Pagina Lista.

Esistono template da seguire?

Grazie

**Comment by AlessandroVecchi** [comment]
Ciao @wmasi78,
I template che dici non ci sono :)
Ma, per come ho interpretato io, si possono applicare gli stessi concetti a tutti le pagine del sito. Fondamentalmente quelle dell'albo sono pagine di lista e di dettaglio.
Considera che i siti che citi sono stati realizzati con la precedente versione del modello e bootstrap-italia 1.x
