### ISSUE TITLE
Accessibilità: è corretto usate i titoli h5 per le card documenti?

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#66]
Ciao,
Collegandomi ad un'[altra discussione](https://github.com/italia/bootstrap-italia/issues/764) mi chiedo se nel template [notizia ](https://italia.github.io/design-comuni-pagine-statiche/sito/template-novita-notizia.html) sia corretto per l'accessibilità utilizzare le card per l'elenco documenti con un titolo H5.
Utilizzare un titolo per un elemento in cui c'è solo il titolo stesso stesso imho non ha molto senso. Non è il titolo di nulla.
Per l'elenco dei documenti secondo me sarebbe più corretto usare una lista.
Si può formattare nello stesso modo ma usando tag diversi.
Cosa ne pensate?

Una nota anche sull'impaginazione: mi chiedo se ha senso formattare i documenti su due colonne con il testo che andrà quasi sempre va a capo. Da considerare che potrebbero esserci molti documenti in una pagina, forse è meglio uno stile più snello.

**Comment by AlessandroVecchi** [comment]
Nella stessa pagina ci sono altre incoerenze:

L’intestazione delle chips degli argomenti è un semplice span

```
        <div class="mt-4 mb-4">
          <div class="row">
            <span class="mb-2 small">Argomenti</span>
          </div>
          <a href="#" class="text-decoration-none">
            <div class="chip chip-simple chip-primary">
              <span class="chip-label">Cultura</span>
            </div>
          </a>
          <a href="#" class="text-decoration-none">
            <div class="chip chip-simple chip-primary">
              <span class="chip-label">Muoversi</span>
            </div>
          </a>
        </div>
```

Mentre per le persone è presente misteriosamente un h6
```
            <div class="col-12 col-sm-4">
              <h6><small>Persone</small></h6>
              <a href="#" class="text-decoration-none">
                <div class="chip chip-simple chip-primary">
                  <span class="chip-label">Mario Rossi</span>
                </div>
              </a>
              <a href="#" class="text-decoration-none">
                <div class="chip chip-simple chip-primary">
                  <span class="chip-label">Alessandro Bianchi</span>
                </div>
              </a>
            </div>
```
Come introduzione al riquadro "in a cura di" inoltre c'è un p con la classe h6
All'interno poi c'è un h5 che anche in questo caso non sono troppo convinto che vada bene
```
            <div class="col-12 col-sm-8">
              <p class="h6"><small>Questa pagina è gestita da</small></p>
              <div class="card-wrapper rounded shadow-sm h-auto">
                <div class="card card-teaser card-teaser-info rounded shadow-sm p-4">
                  <div class="card-body pe-3">
                    <h5 class="card-title">
                      <a class="text-decoration-none" href="#">
                        Assessorato al Turismo
                      </a>
                    </h5>
                    <div class="card-text">
                      <p>Via Roma 1</p>
                      <p>00100 Roma</p>
                    </div>
                  </div>
                  <div class="avatar size-xl">
                    <img src="https://picsum.photos/200/200" alt="Immagine" />
                  </div>
                </div>
              </div>
            </div>
```


Approfitto per segnalare anche un bug grafico

![immagine](https://user-images.githubusercontent.com/20642463/202505228-cdb4b670-68e5-4e16-b631-0d52960037ff.png)

che io ho corretto con
```
            <div class="col-12 col-sm-8 mb-4 mb-sm-0">
              <div class="card-wrapper shadow-sm rounded pb-0">
              ...
```

**Comment by zetareticoli** [comment]
> Nella stessa pagina ci sono altre incoerenze:
> 
> L’intestazione delle chips degli argomenti è un semplice span
> 
> ```
>         <div class="mt-4 mb-4">
>           <div class="row">
>             <span class="mb-2 small">Argomenti</span>
>           </div>
>           <a href="#" class="text-decoration-none">
>             <div class="chip chip-simple chip-primary">
>               <span class="chip-label">Cultura</span>
>             </div>
>           </a>
>           <a href="#" class="text-decoration-none">
>             <div class="chip chip-simple chip-primary">
>               <span class="chip-label">Muoversi</span>
>             </div>
>           </a>
>         </div>
> ```
> 
> Mentre per le persone è presente misteriosamente un h6
> 
> ```
>             <div class="col-12 col-sm-4">
>               <h6><small>Persone</small></h6>
>               <a href="#" class="text-decoration-none">
>                 <div class="chip chip-simple chip-primary">
>                   <span class="chip-label">Mario Rossi</span>
>                 </div>
>               </a>
>               <a href="#" class="text-decoration-none">
>                 <div class="chip chip-simple chip-primary">
>                   <span class="chip-label">Alessandro Bianchi</span>
>                 </div>
>               </a>
>             </div>
> ```
> 
> Come introduzione al riquadro "in a cura di" inoltre c'è un p con la classe h6 All'interno poi c'è un h5 che anche in questo caso non sono troppo convinto che vada bene
> 
> ```
>             <div class="col-12 col-sm-8">
>               <p class="h6"><small>Questa pagina è gestita da</small></p>
>               <div class="card-wrapper rounded shadow-sm h-auto">
>                 <div class="card card-teaser card-teaser-info rounded shadow-sm p-4">
>                   <div class="card-body pe-3">
>                     <h5 class="card-title">
>                       <a class="text-decoration-none" href="#">
>                         Assessorato al Turismo
>                       </a>
>                     </h5>
>                     <div class="card-text">
>                       <p>Via Roma 1</p>
>                       <p>00100 Roma</p>
>                     </div>
>                   </div>
>                   <div class="avatar size-xl">
>                     <img src="https://picsum.photos/200/200" alt="Immagine" />
>                   </div>
>                 </div>
>               </div>
>             </div>
> ```
> 
> Approfitto per segnalare anche un bug grafico
> 
> ![immagine](https://user-images.githubusercontent.com/20642463/202505228-cdb4b670-68e5-4e16-b631-0d52960037ff.png)
> 
> che io ho corretto con
> 
> ```
>             <div class="col-12 col-sm-8 mb-4 mb-sm-0">
>               <div class="card-wrapper shadow-sm rounded pb-0">
>               ...
> ```

Ciao @AlessandroVecchi , grazie per la continua collaborazione sui templates. Ti chiederei solo la cortesia di aprire una issue per ogni bug/segnalazione così da poterle gestire nel modo migliore. Grazie 🙏

**Comment by zetareticoli** [comment]
> Ciao, Collegandomi ad un'[altra discussione](https://github.com/italia/bootstrap-italia/issues/764) mi chiedo se nel template [notizia ](https://italia.github.io/design-comuni-pagine-statiche/sito/template-novita-notizia.html) sia corretto per l'accessibilità utilizzare le card per l'elenco documenti con un titolo H5. Utilizzare un titolo per un elemento in cui c'è solo il titolo stesso stesso imho non ha molto senso. Non è il titolo di nulla. Per l'elenco dei documenti secondo me sarebbe più corretto usare una lista. Si può formattare nello stesso modo ma usando tag diversi. Cosa ne pensate?

Per quanto riguarda l'accessibilità, è importante garantire una corretta fruizione dei contenuti a chi naviga con strumenti alternativi (vedi screen reader). In questo caso, quindi, la navigazione per _headings_ porterebbe l'utente dal titolo "Documenti" al successivo titolo del documento. Il che non è sbagliato, ma forse poco chiaro. 

La sola presenza del titolo senza altro contenuto non è considerato un problema di accessibilità.

Il suggerimento di usare una lista per l'elenco dei documenti è valido, e potrebbe essere oggetto di miglioria, così come la valutazione dello spazio occupato. 👈 **Teniamo questo come oggetto della issue** 

> 
> Una nota anche sull'impaginazione: mi chiedo se ha senso formattare i documenti su due colonne con il testo che andrà quasi sempre va a capo. Da considerare che potrebbero esserci molti documenti in una pagina, forse è meglio uno stile più snello.

**Comment by AlessandroVecchi** [comment]
Ciao @zetareticoli,
Ok, in realtà mi dispiaceva aprire tante issee diverse, mi sembrerebbe di apparire un po' pedante.
per l'elenco documenti io ho formattato in questo modo

```
          <ul>
            <li class="card card-teaser shadow-sm rounded border border-light mb-2">
              <svg class="icon" aria-hidden="true">
                <use xlink:href="~/bootstrap-italia/svg/sprites.svg#it-clip"></use>
              </svg>
              <div class="card-body">
                <div class="card-title mb-0">
                  <a class="text-decoration-none fw-semibold" href="#" title="Scarica Lo speciale di National Geographic sulle regate in
                    Sardegna" aria-label="Scarica Lo speciale di National Geographic sulle regate in
                    Sardegna">
                    Lo speciale di National Geographic sulle regate in Sardegna
                  </a>
                  <span class="font-xs text-muted">[.pdf 115,22 Kb - 30/08/2022]</span>
                </div>
              </div>
            </li>
            <li class="card card-teaser shadow-sm rounded border border-light mb-2">
              <svg class="icon" aria-hidden="true">
                <use xlink:href="~/bootstrap-italia/svg/sprites.svg#it-clip"></use>
              </svg>
              <div class="card-body">
                <div class="card-title mb-0">
                  <a class="text-decoration-none fw-semibold" href="#" title="Scarica Le rotte del mare: porti e approdi sulle coste
                    dell'Isola" aria-label="Scarica Le rotte del mare: porti e approdi sulle coste
                    dell'Isola">
                    Le rotte del mare: porti e approdi sulle coste dell'Isola
                  </a>
                  <span class="font-xs text-muted">[.pdf 115,22 Kb - 30/08/2022]</span>
                </div>
              </div>
            </li>
          </ul>
```
(ci sono anche alcune mie personalizzazioni)
