### ISSUE TITLE
Componenti Hero e Heading

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#77]
Ciao,
Non so se considerarla una vera e propria issue ma...

In alcuni template, per l'intestazione della pagina, viene usato perlopiù il componente Hero, in altre viene usato Heading/Heading-detail e altre ancora non ne usano nessuno.
Mi chiedo se ha senso avere questi pezzi di codice diversi per la stessa funzione...

Inoltre Hero è un componente effettivamente presente in bootstrap-italia mentre non ho trovato traccia di Heading che presumo sia stato creato appositamente per questo progetto.

Da considerare inoltre che l'uso del componente Hero per l’introduzione della pagina mi sembra un po' una forzatura.

Nel dettaglio dei file HTML presenti qui: https://italia.github.io/design-comuni-pagine-statiche/sito/index.html per il sito pubblico
Questi utilizzano **cmpHero**:
template-amministrazione.html
template-argomenti.html
template-documenti.html
template-novita.html
template-servizi.html
template-servizi-servizio.html
template-vivi.html
domande-frequenti.html

Questa **cmpHeading**
template-dettaglio-servizio.html

Questi non usano un componente ma replicano più o meno la stessa cosa di cmpHeading
template-argomenti-argomento.html
template-evento.html
template-novita-notizia.html
template-risultati.html

**Comment by zetareticoli** [comment]
Ciao @AlessandroVecchi,
abbiamo nei piani l'ottimizzazione dell'uso dei componenti, sopratutto perché stiamo aggiungendo nuovi _templates_ mancanti nella v2. 

Intanto, ti ringrazio per il lavoro di analisi sull'utilizzo nei templates, ci è molto utile.
