### ISSUE TITLE
Incongruenza tra le pagine

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#80]
Ciao,
Segnalo le notevole incongruenza di codice tra la pagina https://italia.github.io/design-comuni-pagine-statiche/sito/template-dettaglio-servizio.html e la pagina https://italia.github.io/design-comuni-pagine-statiche/sito/template-novita-notizia.html

In entrambi i casi, salvo alcune differenze legate al tipo di contenuto, si tratta di pagine di dettaglio con la medesima struttura e quindi non trovo motivazioni reali per queste incongruenze.
Mi riferisco in particolare alla parte centrale con l'indice sulla sinistra e i contenuti sulla destra.

Questo è un estratto dal codice sorgente della pagina template-novita-notizia

```
 <div class="container">
    <div class="row border-top border-light row-column-border row-column-menu-left">
      <aside class="col-lg-4">
        {{>cmp-navscroll/cmp-navscroll accordion-title="INDICE DELLA PAGINA" id="one"
        link-list=link-list.template-novita-notizia}}
      </aside>
      <section class="col-lg-8 it-page-sections-container border-light">
        <article id="descrizione" class="it-page-section anchor-offset" data-audio>
          <h2 class="mb-3">Descrizione</h2>
          <p class="font-serif">
            Vivamus orci risus, fringilla sit amet enim vel, semper faucibus
            elit. Aliquam nec laoreet leo. Integer eu venenatis purus, eu
            tincidunt eros. Aliquam egestas est quis lacinia ultrices.
            Vestibulum vehicula sit amet purus id suscipit. Sed gravida urna
            tellus, sed aliquet erat faucibus porta. Aenean condimentum.
          </p>
        </article>
```

Questo della pagina template-dettaglio-servizio

```
  <div class="container">
    <div class="row row-column-menu-left mt-4 mt-lg-80 pb-lg-80 pb-40">
      <div class="col-12 col-lg-3 mb-4 border-col">
        {{>cmp-navscroll/cmp-navscroll accordion-title="INDICE DELLA PAGINA"  id="one"
        link-list=link-list.template-dettaglio-servizio}}
      </div>

      <div class="col-12 col-lg-8 offset-lg-1">
        <div class="it-page-sections-container">
        <section class="it-page-section mb-30" id="who-needs">
          <h2 class="mb-3">A chi è rivolto</h2>
          <div class="richtext-wrapper lora">
            <ul>
              <li><span>Bambini di età compresa tra i 3 e i 5 anni compiuti o da compiere entro il 31 dicembre di ogni anno.</span></li>
              <li><span>Bambini che compiranno i 3 anni dopo il 31 dicembre e, comunque, entro e non oltre il 30 aprile dell’anno successivo (ammissione anticipata).</span></li>
            </ul>
          </div>
        </section>
```

Mi sembra uno spreco di codice e di stili con ampio margine di ottimizzazione.
Da parte mia userò lo stesso codice degli avvisi anche per i servizi (ovviamente non sarà un article ma un div)

Segnalo inoltre che su slack c'era un segnalazione, che ora non trovo, sull'errato utilizzo di `<article>` e `<section>` negli avvisi. Andrebbero sostanzialmente invertiti.

**Comment by zetareticoli** [comment]
Ciao @AlessandroVecchi , sono d'accordo con te sulla necessità di standardizzare ed ottimizzare la struttura HTML dei templates. 

Visto che ci stai lavorando, potresti aprire una PR di modifica da mettere a riuso ;)

**Comment by AlessandroVecchi** [comment]
> Ciao @AlessandroVecchi , sono d'accordo con te sulla necessità di standardizzare ed ottimizzare la struttura HTML dei templates.
> 
> Visto che ci stai lavorando, potresti aprire una PR di modifica da mettere a riuso ;)

Ciao, mi piacerebbe ma mi manca il tempo, io devo produrre :)

**Comment by enrimk** [comment]
> Segnalo inoltre che su slack c'era un segnalazione, che ora non trovo, sull'errato utilizzo di `<article>` e `<section>` negli avvisi. Andrebbero sostanzialmente invertiti.

Non (solo?) su Slack: era la #44.
_Wontfix_, [a quanto pare](https://github.com/italia/design-comuni-pagine-statiche/blob/main/src/pages/sito/novita-dettaglio.hbs#L151-L152).
