### ISSUE TITLE
Template Evento: titolo H2 e date

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-pagine-statiche#81]
Ciao,
Nel [template di dettaglio di un evento](https://italia.github.io/design-comuni-pagine-statiche/sito/evento-dettaglio.html) è stato usato un H2 per la data.
Non sono sicuro che sia una scelta corretta ai fini dell'accessibilità e della semantica oltre a non essere coerente col le altre pagine (negli avvisi per la data è stato usato un P).
Non essendo propriamente un sottotitolo forse è preferibile sostituire l'h2 con un generico DIV?

Ho notato inoltre che nessuna della date presente sul modello è marcata con il tag <time>
es. `<time datetime="2022-11-08">8 novembre 2022</time>`
è una scelta voluta? se sì, qual è stata la motivazione di questa scelta?
Grazie

**Comment by astagi** [comment]
@AlessandroVecchi probabilmente la segnalazione è vecchia, la chiudo. Per la parte di tag <time> possiamo pensare a dove inserirlo (va prevista poi per tutti i temi di CMS derivanti dallo statico). Nel caso apri una issue ad hoc.

**Comment by AlessandroVecchi** [comment]
Ciao, in che senso "è vecchia"? è cambiato qualcosa nel frattempo?
